version: "3.7"

services:
  instagram_db:
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  node_app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - instagram_db
    volumes:
      - .:/app
    command: node server.js
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
